### ISSUE TITLE
Moreores init referencing non-existent file

### ISSUE THREAD

**Issue by Awkanimus** [sfence/adaptation_modpack#1]
Seems like the file in adaptation_modpack references `/moreores.lua` but it doesn't exist.

https://github.com/sfence/adaptation_modpack/blob/c4144627b201a6b118e610d35b548a3047e891df/adaptation_moreores/init.lua#L5

**Comment by sfence** [comment]
Should be fixed with 321280552cb9f8693c352de881fbfc5b7aba1002 .

Thanks for reporing.
